"""claude-cleanup: Stage and commit Claude Code transient state files.

Knows which .claude/ subdirectories are "noise" (auto-generated by Claude Code)
vs "user work" (hand-edited configs, agents, skills, etc.). Stages only the
noise files, optionally commits them, and reports what user files remain.

Use --user to stage user artifacts instead of noise (separate commit).

Designed to run fast and be repeatable -- run multiple times to catch files
Claude Code creates while you're working.
"""

import argparse
import subprocess
import sys
import os


# --- Noise directories: auto-generated Claude Code state ---
# These are safe to bulk-commit without review.
NOISE_DIRS = [
    ".claude/debug",
    ".claude/file-history",
    ".claude/paste-cache",
    ".claude/session-states",
    ".claude/sessions",
    ".claude/shell-snapshots",
    ".claude/telemetry",
    ".claude/logs",
    ".claude/tasks",
]

# --- Noise files: individual auto-generated files ---
NOISE_FILES = [
    ".claude/cache/changelog.md",
    ".claude/.credentials.json",
    ".claude/mcp-needs-auth-cache.json",
]

# --- User directories: hand-edited, require separate commit ---
# Listed here for reference / --status reporting only.
USER_DIRS = [
    ".claude/agents",
    ".claude/backups",
    ".claude/commands",
    ".claude/image-cache",
    ".claude/plans",
    ".claude/plugins",
    ".claude/private",
    ".claude/sesslogs",
    ".claude/skills",
    ".claude/todos",
]

USER_FILES = [
    ".claude/CLAUDE.md",
    ".claude/settings.json",
    ".claude/settings.local.json",
]


def git(*args):
    """Run a git command and return (returncode, stdout, stderr)."""
    result = subprocess.run(
        ["git"] + list(args),
        capture_output=True,
        text=True,
    )
    return result.returncode, result.stdout, result.stderr


def find_repo_root():
    """Find the git repo root from cwd."""
    rc, out, _ = git("rev-parse", "--show-toplevel")
    if rc != 0:
        print("Error: not inside a git repository.", file=sys.stderr)
        sys.exit(1)
    return out.strip()


def get_noise_status(repo_root):
    """Get git status filtered to noise paths only."""
    rc, out, _ = git("status", "--short")
    if rc != 0:
        return []

    noise_lines = []
    for line in out.splitlines():
        # status lines are like " M .claude/debug/foo.txt" or "?? .claude/sessions/bar"
        if len(line) < 4:
            continue
        filepath = line[3:]
        for d in NOISE_DIRS:
            if filepath.startswith(d + "/") or filepath == d:
                noise_lines.append(line)
                break
        else:
            for f in NOISE_FILES:
                if filepath == f:
                    noise_lines.append(line)
                    break

    return noise_lines


def get_user_status():
    """Get git status filtered to user paths only."""
    rc, out, _ = git("status", "--short")
    if rc != 0:
        return []

    user_lines = []
    for line in out.splitlines():
        if len(line) < 4:
            continue
        filepath = line[3:]
        for d in USER_DIRS:
            if filepath.startswith(d + "/") or filepath == d:
                user_lines.append(line)
                break
        else:
            for f in USER_FILES:
                if filepath == f:
                    user_lines.append(line)
                    break

    return user_lines


def get_unknown_status():
    """Get git status for .claude/ files that are neither noise nor user."""
    rc, out, _ = git("status", "--short")
    if rc != 0:
        return []

    all_noise = set()
    all_user = set()

    for line in out.splitlines():
        if len(line) < 4:
            continue
        filepath = line[3:]
        if not filepath.startswith(".claude/"):
            continue

        is_noise = False
        for d in NOISE_DIRS:
            if filepath.startswith(d + "/") or filepath == d:
                is_noise = True
                break
        if not is_noise:
            for f in NOISE_FILES:
                if filepath == f:
                    is_noise = True
                    break

        if is_noise:
            all_noise.add(filepath)
            continue

        is_user = False
        for d in USER_DIRS:
            if filepath.startswith(d + "/") or filepath == d:
                is_user = True
                break
        if not is_user:
            for f in USER_FILES:
                if filepath == f:
                    is_user = True
                    break

        if is_user:
            all_user.add(filepath)
            continue

        # Neither noise nor user -- unknown
        yield line


def stage_noise():
    """Stage all noise directories and files."""
    targets = []
    for d in NOISE_DIRS:
        if os.path.exists(d):
            targets.append(d)
        else:
            # Directory might have been deleted -- still need to stage the deletion
            targets.append(d)

    for f in NOISE_FILES:
        targets.append(f)

    if not targets:
        print("Nothing to stage.")
        return 0

    rc, out, err = git("add", *targets)
    if rc != 0:
        print(f"git add failed: {err}", file=sys.stderr)
        return rc

    # Count what was staged
    rc2, diff_out, _ = git("diff", "--cached", "--stat")
    if rc2 == 0 and diff_out.strip():
        # Last line of --stat is the summary
        lines = diff_out.strip().splitlines()
        print(f"Staged: {lines[-1].strip()}")
    else:
        print("Staged noise files (no diff summary available).")

    return 0


def stage_user():
    """Stage all user directories and files."""
    targets = []
    for d in USER_DIRS:
        targets.append(d)
    for f in USER_FILES:
        targets.append(f)

    if not targets:
        print("Nothing to stage.")
        return 0

    rc, out, err = git("add", *targets)
    if rc != 0:
        print(f"git add failed: {err}", file=sys.stderr)
        return rc

    # Count what was staged
    rc2, diff_out, _ = git("diff", "--cached", "--stat")
    if rc2 == 0 and diff_out.strip():
        lines = diff_out.strip().splitlines()
        print(f"Staged: {lines[-1].strip()}")
    else:
        print("Staged user files (no diff summary available).")

    return 0


def commit_with_message(message):
    """Commit staged files with the given message."""
    rc, out, err = git("commit", "-m", message)
    if rc != 0:
        if "nothing to commit" in (out + err):
            print("Nothing to commit -- working tree clean.")
            return 0
        print(f"Commit failed: {err}", file=sys.stderr)
        return rc

    print(out.strip())
    return 0


DEFAULT_NOISE_MSG = "~/.claude noise: sync transient state files"
DEFAULT_USER_MSG = "~/.claude: sync user configs, skills, session logs, and plugins"


def commit_noise(message=None):
    """Commit staged noise files."""
    return commit_with_message(message or DEFAULT_NOISE_MSG)


def main():
    parser = argparse.ArgumentParser(
        description="Stage and commit Claude Code transient state files.",
        epilog=(
            "Run without flags to stage noise files. "
            "Use --user to stage user files instead. "
            "Use --commit to also commit them."
        ),
    )
    parser.add_argument(
        "--user", "-u",
        action="store_true",
        help="Stage user files instead of noise files",
    )
    parser.add_argument(
        "--commit", "-c",
        action="store_true",
        help="Commit after staging",
    )
    parser.add_argument(
        "--message", "-m",
        type=str,
        default=None,
        help="Custom commit message (implies --commit)",
    )
    parser.add_argument(
        "--status", "-s",
        action="store_true",
        help="Show status breakdown: noise vs user vs unknown .claude/ files",
    )
    parser.add_argument(
        "--dry-run", "-n",
        action="store_true",
        help="Show what would be staged without actually staging",
    )

    args = parser.parse_args()

    # If --message provided, implies --commit
    if args.message:
        args.commit = True

    # Ensure we're in a git repo
    repo_root = find_repo_root()

    if args.status:
        noise = get_noise_status(repo_root)
        user = get_user_status()
        unknown = list(get_unknown_status())

        print(f"=== NOISE ({len(noise)} files) === [auto-staged by claude-cleanup]")
        for line in noise[:10]:
            print(f"  {line}")
        if len(noise) > 10:
            print(f"  ... and {len(noise) - 10} more")

        print(f"\n=== USER ({len(user)} files) === [staged by claude-cleanup --user]")
        for line in user:
            print(f"  {line}")

        if unknown:
            print(f"\n=== UNKNOWN ({len(unknown)} files) === [not categorized]")
            for line in unknown:
                print(f"  {line}")
            print("\nConsider adding unknown paths to NOISE_DIRS/NOISE_FILES or USER_DIRS/USER_FILES.")

        return

    if args.dry_run:
        if args.user:
            items = get_user_status()
            label = "user"
        else:
            items = get_noise_status(repo_root)
            label = "noise"
        print(f"Would stage {len(items)} {label} files:")
        for line in items[:20]:
            print(f"  {line}")
        if len(items) > 20:
            print(f"  ... and {len(items) - 20} more")
        return

    if args.user:
        # Stage user files
        rc = stage_user()
        if rc != 0:
            sys.exit(rc)

        if args.commit:
            rc = commit_with_message(args.message or DEFAULT_USER_MSG)
            if rc != 0:
                sys.exit(rc)

            # Show remaining unknown files
            unknown = list(get_unknown_status())
            if unknown:
                print(f"\nRemaining unknown files ({len(unknown)}):")
                for line in unknown:
                    print(f"  {line}")
    else:
        # Stage noise files (default)
        rc = stage_noise()
        if rc != 0:
            sys.exit(rc)

        if args.commit:
            rc = commit_noise(args.message)
            if rc != 0:
                sys.exit(rc)

            # Show remaining user files
            user = get_user_status()
            if user:
                print(f"\nRemaining user files ({len(user)}):")
                for line in user:
                    print(f"  {line}")


if __name__ == "__main__":
    main()
